# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './base/gui_base.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gui(object):
    def setupUi(self, Gui):
        Gui.setObjectName("Gui")
        Gui.resize(874, 724)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Gui.sizePolicy().hasHeightForWidth())
        Gui.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Gui.setFont(font)
        Gui.setMouseTracking(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Gui)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Gui)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(850, 700))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1000000, 10000000))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.plotsButton = QtWidgets.QPushButton(self.page)
        self.plotsButton.setMinimumSize(QtCore.QSize(120, 30))
        self.plotsButton.setMaximumSize(QtCore.QSize(100, 50))
        self.plotsButton.setObjectName("plotsButton")
        self.horizontalLayout_27.addWidget(self.plotsButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(self.page)
        self.closeButton.setMinimumSize(QtCore.QSize(120, 30))
        self.closeButton.setMaximumSize(QtCore.QSize(120, 50))
        self.closeButton.setSizeIncrement(QtCore.QSize(100, 5))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_27.addWidget(self.closeButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        self.inputFileFrame = QtWidgets.QFrame(self.page)
        self.inputFileFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.inputFileFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.inputFileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputFileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputFileFrame.setObjectName("inputFileFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.inputFileFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.inputFileText = QtWidgets.QLabel(self.inputFileFrame)
        self.inputFileText.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.inputFileText.setFont(font)
        self.inputFileText.setObjectName("inputFileText")
        self.horizontalLayout_29.addWidget(self.inputFileText)
        self.showInputDataButton = QtWidgets.QPushButton(self.inputFileFrame)
        self.showInputDataButton.setEnabled(False)
        self.showInputDataButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.showInputDataButton.setAccessibleName("")
        self.showInputDataButton.setObjectName("showInputDataButton")
        self.horizontalLayout_29.addWidget(self.showInputDataButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_29, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outputFileText = QtWidgets.QLabel(self.inputFileFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFileText.sizePolicy().hasHeightForWidth())
        self.outputFileText.setSizePolicy(sizePolicy)
        self.outputFileText.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.outputFileText.setFont(font)
        self.outputFileText.setObjectName("outputFileText")
        self.horizontalLayout.addWidget(self.outputFileText)
        self.showObservationsDataButton = QtWidgets.QPushButton(self.inputFileFrame)
        self.showObservationsDataButton.setEnabled(False)
        self.showObservationsDataButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.showObservationsDataButton.setObjectName("showObservationsDataButton")
        self.horizontalLayout.addWidget(self.showObservationsDataButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inputFileEdit = QtWidgets.QLineEdit(self.inputFileFrame)
        self.inputFileEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.inputFileEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.inputFileEdit.setFont(font)
        self.inputFileEdit.setObjectName("inputFileEdit")
        self.horizontalLayout_3.addWidget(self.inputFileEdit)
        self.inputFileButton = QtWidgets.QPushButton(self.inputFileFrame)
        self.inputFileButton.setMinimumSize(QtCore.QSize(0, 22))
        self.inputFileButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.inputFileButton.setFont(font)
        self.inputFileButton.setObjectName("inputFileButton")
        self.horizontalLayout_3.addWidget(self.inputFileButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputFileEdit = QtWidgets.QLineEdit(self.inputFileFrame)
        self.outputFileEdit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.outputFileEdit.setFont(font)
        self.outputFileEdit.setObjectName("outputFileEdit")
        self.horizontalLayout_2.addWidget(self.outputFileEdit)
        self.outputFileButton = QtWidgets.QPushButton(self.inputFileFrame)
        self.outputFileButton.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.outputFileButton.setFont(font)
        self.outputFileButton.setObjectName("outputFileButton")
        self.horizontalLayout_2.addWidget(self.outputFileButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.inputFileFrame)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.alfaFrame = QtWidgets.QFrame(self.page)
        self.alfaFrame.setMinimumSize(QtCore.QSize(280, 45))
        self.alfaFrame.setMaximumSize(QtCore.QSize(250, 50))
        self.alfaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alfaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alfaFrame.setObjectName("alfaFrame")
        self.aphaInputFileText = QtWidgets.QLabel(self.alfaFrame)
        self.aphaInputFileText.setGeometry(QtCore.QRect(13, 13, 134, 16))
        self.aphaInputFileText.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.aphaInputFileText.setFont(font)
        self.aphaInputFileText.setObjectName("aphaInputFileText")
        self.alphaDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.alfaFrame)
        self.alphaDoubleSpinBox.setGeometry(QtCore.QRect(155, 13, 82, 20))
        self.alphaDoubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.alphaDoubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.alphaDoubleSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.alphaDoubleSpinBox.setSuffix("")
        self.alphaDoubleSpinBox.setDecimals(2)
        self.alphaDoubleSpinBox.setMinimum(0.01)
        self.alphaDoubleSpinBox.setMaximum(1.0)
        self.alphaDoubleSpinBox.setSingleStep(0.01)
        self.alphaDoubleSpinBox.setProperty("value", 0.5)
        self.alphaDoubleSpinBox.setObjectName("alphaDoubleSpinBox")
        self.horizontalLayout_14.addWidget(self.alfaFrame)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.uncertaintyCheckBox = QtWidgets.QCheckBox(self.page)
        self.uncertaintyCheckBox.setObjectName("uncertaintyCheckBox")
        self.horizontalLayout_14.addWidget(self.uncertaintyCheckBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.modelsFrame = QtWidgets.QFrame(self.page)
        self.modelsFrame.setMinimumSize(QtCore.QSize(0, 120))
        self.modelsFrame.setMaximumSize(QtCore.QSize(100000, 100000))
        self.modelsFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.modelsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modelsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modelsFrame.setObjectName("modelsFrame")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.modelsFrame)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem5)
        self.modelsTabWidget = QtWidgets.QTabWidget(self.modelsFrame)
        self.modelsTabWidget.setMinimumSize(QtCore.QSize(100, 140))
        self.modelsTabWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.modelsTabWidget.setObjectName("modelsTabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.PFMcheckBox = QtWidgets.QCheckBox(self.widget)
        self.PFMcheckBox.setObjectName("PFMcheckBox")
        self.horizontalLayout_48.addWidget(self.PFMcheckBox)
        self.PFMwrnLabel = QtWidgets.QLabel(self.widget)
        self.PFMwrnLabel.setText("")
        self.PFMwrnLabel.setObjectName("PFMwrnLabel")
        self.horizontalLayout_48.addWidget(self.PFMwrnLabel)
        self.gridLayout_5.addLayout(self.horizontalLayout_48, 0, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.EMcheckBox = QtWidgets.QCheckBox(self.widget)
        self.EMcheckBox.setObjectName("EMcheckBox")
        self.horizontalLayout_26.addWidget(self.EMcheckBox)
        self.EMwrnLabel = QtWidgets.QLabel(self.widget)
        self.EMwrnLabel.setText("")
        self.EMwrnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EMwrnLabel.setObjectName("EMwrnLabel")
        self.horizontalLayout_26.addWidget(self.EMwrnLabel)
        self.gridLayout_5.addLayout(self.horizontalLayout_26, 0, 1, 1, 1)
        self.PFM_GroupBox = QtWidgets.QGroupBox(self.widget)
        self.PFM_GroupBox.setEnabled(False)
        self.PFM_GroupBox.setMinimumSize(QtCore.QSize(40, 100))
        self.PFM_GroupBox.setTitle("")
        self.PFM_GroupBox.setObjectName("PFM_GroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PFM_GroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PFM_timeGroupBox = QtWidgets.QGroupBox(self.PFM_GroupBox)
        self.PFM_timeGroupBox.setEnabled(False)
        self.PFM_timeGroupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.PFM_timeGroupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.PFM_timeGroupBox.setTitle("")
        self.PFM_timeGroupBox.setObjectName("PFM_timeGroupBox")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.PFM_timeGroupBox)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.PFM_timeLabel = QtWidgets.QLabel(self.PFM_timeGroupBox)
        self.PFM_timeLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.PFM_timeLabel.setObjectName("PFM_timeLabel")
        self.horizontalLayout_19.addWidget(self.PFM_timeLabel)
        self.PFM_timeDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.PFM_timeGroupBox)
        self.PFM_timeDoubleSpinBox_1.setMinimumSize(QtCore.QSize(60, 25))
        self.PFM_timeDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.PFM_timeDoubleSpinBox_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.PFM_timeDoubleSpinBox_1.setSuffix("")
        self.PFM_timeDoubleSpinBox_1.setMinimum(0.01)
        self.PFM_timeDoubleSpinBox_1.setMaximum(1000000.0)
        self.PFM_timeDoubleSpinBox_1.setSingleStep(0.01)
        self.PFM_timeDoubleSpinBox_1.setObjectName("PFM_timeDoubleSpinBox_1")
        self.horizontalLayout_19.addWidget(self.PFM_timeDoubleSpinBox_1)
        self.PFM_timeDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.PFM_timeGroupBox)
        self.PFM_timeDoubleSpinBox_2.setMinimumSize(QtCore.QSize(60, 25))
        self.PFM_timeDoubleSpinBox_2.setSuffix("")
        self.PFM_timeDoubleSpinBox_2.setMinimum(0.01)
        self.PFM_timeDoubleSpinBox_2.setMaximum(1000000.0)
        self.PFM_timeDoubleSpinBox_2.setSingleStep(0.01)
        self.PFM_timeDoubleSpinBox_2.setObjectName("PFM_timeDoubleSpinBox_2")
        self.horizontalLayout_19.addWidget(self.PFM_timeDoubleSpinBox_2)
        self.horizontalLayout_4.addWidget(self.PFM_timeGroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.PFM_betaCheckBox = QtWidgets.QCheckBox(self.PFM_GroupBox)
        self.PFM_betaCheckBox.setObjectName("PFM_betaCheckBox")
        self.horizontalLayout_13.addWidget(self.PFM_betaCheckBox)
        self.PFM_betaGroupBox = QtWidgets.QGroupBox(self.PFM_GroupBox)
        self.PFM_betaGroupBox.setEnabled(False)
        self.PFM_betaGroupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.PFM_betaGroupBox.setTitle("")
        self.PFM_betaGroupBox.setObjectName("PFM_betaGroupBox")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.PFM_betaGroupBox)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.PFM_betaDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.PFM_betaGroupBox)
        self.PFM_betaDoubleSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.PFM_betaDoubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.PFM_betaDoubleSpinBox.setSuffix("")
        self.PFM_betaDoubleSpinBox.setMinimum(0.01)
        self.PFM_betaDoubleSpinBox.setMaximum(1.0)
        self.PFM_betaDoubleSpinBox.setSingleStep(0.01)
        self.PFM_betaDoubleSpinBox.setObjectName("PFM_betaDoubleSpinBox")
        self.horizontalLayout_18.addWidget(self.PFM_betaDoubleSpinBox)
        self.horizontalLayout_13.addWidget(self.PFM_betaGroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.gridLayout_5.addWidget(self.PFM_GroupBox, 1, 0, 1, 1)
        self.EM_GroupBox = QtWidgets.QGroupBox(self.widget)
        self.EM_GroupBox.setEnabled(False)
        self.EM_GroupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.EM_GroupBox.setTitle("")
        self.EM_GroupBox.setObjectName("EM_GroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.EM_GroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.EM_timeGroupBox = QtWidgets.QGroupBox(self.EM_GroupBox)
        self.EM_timeGroupBox.setEnabled(False)
        self.EM_timeGroupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.EM_timeGroupBox.setTitle("")
        self.EM_timeGroupBox.setObjectName("EM_timeGroupBox")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.EM_timeGroupBox)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.EM_timeLabel = QtWidgets.QLabel(self.EM_timeGroupBox)
        self.EM_timeLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.EM_timeLabel.setObjectName("EM_timeLabel")
        self.horizontalLayout_24.addWidget(self.EM_timeLabel)
        self.EM_timeDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.EM_timeGroupBox)
        self.EM_timeDoubleSpinBox_1.setMinimumSize(QtCore.QSize(60, 25))
        self.EM_timeDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EM_timeDoubleSpinBox_1.setSuffix("")
        self.EM_timeDoubleSpinBox_1.setMinimum(0.1)
        self.EM_timeDoubleSpinBox_1.setMaximum(1000000.0)
        self.EM_timeDoubleSpinBox_1.setSingleStep(0.01)
        self.EM_timeDoubleSpinBox_1.setObjectName("EM_timeDoubleSpinBox_1")
        self.horizontalLayout_24.addWidget(self.EM_timeDoubleSpinBox_1)
        self.EM_timeDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.EM_timeGroupBox)
        self.EM_timeDoubleSpinBox_2.setMinimumSize(QtCore.QSize(60, 25))
        self.EM_timeDoubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EM_timeDoubleSpinBox_2.setSuffix("")
        self.EM_timeDoubleSpinBox_2.setMinimum(0.1)
        self.EM_timeDoubleSpinBox_2.setMaximum(1000000.0)
        self.EM_timeDoubleSpinBox_2.setSingleStep(0.01)
        self.EM_timeDoubleSpinBox_2.setObjectName("EM_timeDoubleSpinBox_2")
        self.horizontalLayout_24.addWidget(self.EM_timeDoubleSpinBox_2)
        self.horizontalLayout_11.addWidget(self.EM_timeGroupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.EM_betaCheckBox = QtWidgets.QCheckBox(self.EM_GroupBox)
        self.EM_betaCheckBox.setObjectName("EM_betaCheckBox")
        self.horizontalLayout_12.addWidget(self.EM_betaCheckBox)
        self.EM_betaGroupBox = QtWidgets.QGroupBox(self.EM_GroupBox)
        self.EM_betaGroupBox.setEnabled(False)
        self.EM_betaGroupBox.setMinimumSize(QtCore.QSize(60, 60))
        self.EM_betaGroupBox.setTitle("")
        self.EM_betaGroupBox.setObjectName("EM_betaGroupBox")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.EM_betaGroupBox)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.EM_betaDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.EM_betaGroupBox)
        self.EM_betaDoubleSpinBox.setMinimumSize(QtCore.QSize(90, 25))
        self.EM_betaDoubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EM_betaDoubleSpinBox.setSuffix("")
        self.EM_betaDoubleSpinBox.setMinimum(0.01)
        self.EM_betaDoubleSpinBox.setMaximum(1.0)
        self.EM_betaDoubleSpinBox.setSingleStep(0.01)
        self.EM_betaDoubleSpinBox.setObjectName("EM_betaDoubleSpinBox")
        self.horizontalLayout_23.addWidget(self.EM_betaDoubleSpinBox)
        self.horizontalLayout_12.addWidget(self.EM_betaGroupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.gridLayout_5.addWidget(self.EM_GroupBox, 1, 1, 1, 1)
        self.modelsTabWidget.addTab(self.widget, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.EPMcheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.EPMcheckBox.setObjectName("EPMcheckBox")
        self.horizontalLayout_49.addWidget(self.EPMcheckBox)
        self.EPMwrnLabel = QtWidgets.QLabel(self.tab_4)
        self.EPMwrnLabel.setText("")
        self.EPMwrnLabel.setObjectName("EPMwrnLabel")
        self.horizontalLayout_49.addWidget(self.EPMwrnLabel)
        self.gridLayout_6.addLayout(self.horizontalLayout_49, 0, 0, 1, 1)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.DMcheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.DMcheckBox.setObjectName("DMcheckBox")
        self.horizontalLayout_50.addWidget(self.DMcheckBox)
        self.DMwrnLabel = QtWidgets.QLabel(self.tab_4)
        self.DMwrnLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DMwrnLabel.setText("")
        self.DMwrnLabel.setObjectName("DMwrnLabel")
        self.horizontalLayout_50.addWidget(self.DMwrnLabel)
        self.gridLayout_6.addLayout(self.horizontalLayout_50, 0, 1, 1, 1)
        self.EPM_GroupBox = QtWidgets.QGroupBox(self.tab_4)
        self.EPM_GroupBox.setEnabled(False)
        self.EPM_GroupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.EPM_GroupBox.setMaximumSize(QtCore.QSize(16777215, 10000000))
        self.EPM_GroupBox.setTitle("")
        self.EPM_GroupBox.setObjectName("EPM_GroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.EPM_GroupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.EPM_timeGroupBox = QtWidgets.QGroupBox(self.EPM_GroupBox)
        self.EPM_timeGroupBox.setEnabled(False)
        self.EPM_timeGroupBox.setTitle("")
        self.EPM_timeGroupBox.setObjectName("EPM_timeGroupBox")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.EPM_timeGroupBox)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.EPM_timeLabel = QtWidgets.QLabel(self.EPM_timeGroupBox)
        self.EPM_timeLabel.setObjectName("EPM_timeLabel")
        self.horizontalLayout_15.addWidget(self.EPM_timeLabel)
        self.EPM_timeDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.EPM_timeGroupBox)
        self.EPM_timeDoubleSpinBox_1.setMinimumSize(QtCore.QSize(60, 25))
        self.EPM_timeDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EPM_timeDoubleSpinBox_1.setSuffix("")
        self.EPM_timeDoubleSpinBox_1.setMinimum(0.1)
        self.EPM_timeDoubleSpinBox_1.setMaximum(1000000.0)
        self.EPM_timeDoubleSpinBox_1.setSingleStep(0.01)
        self.EPM_timeDoubleSpinBox_1.setObjectName("EPM_timeDoubleSpinBox_1")
        self.horizontalLayout_15.addWidget(self.EPM_timeDoubleSpinBox_1)
        self.EPM_timeDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.EPM_timeGroupBox)
        self.EPM_timeDoubleSpinBox_2.setMinimumSize(QtCore.QSize(60, 25))
        self.EPM_timeDoubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EPM_timeDoubleSpinBox_2.setSuffix("")
        self.EPM_timeDoubleSpinBox_2.setMinimum(0.1)
        self.EPM_timeDoubleSpinBox_2.setMaximum(1000000.0)
        self.EPM_timeDoubleSpinBox_2.setSingleStep(0.01)
        self.EPM_timeDoubleSpinBox_2.setObjectName("EPM_timeDoubleSpinBox_2")
        self.horizontalLayout_15.addWidget(self.EPM_timeDoubleSpinBox_2)
        self.horizontalLayout_5.addWidget(self.EPM_timeGroupBox)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.EPM_etaGroupBox = QtWidgets.QGroupBox(self.EPM_GroupBox)
        self.EPM_etaGroupBox.setEnabled(False)
        self.EPM_etaGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.EPM_etaGroupBox.setMaximumSize(QtCore.QSize(16777215, 166666))
        self.EPM_etaGroupBox.setTitle("")
        self.EPM_etaGroupBox.setObjectName("EPM_etaGroupBox")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.EPM_etaGroupBox)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.EPM_etaLabel = QtWidgets.QLabel(self.EPM_etaGroupBox)
        self.EPM_etaLabel.setObjectName("EPM_etaLabel")
        self.horizontalLayout_16.addWidget(self.EPM_etaLabel)
        self.EPM_etaDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.EPM_etaGroupBox)
        self.EPM_etaDoubleSpinBox_1.setMinimumSize(QtCore.QSize(0, 25))
        self.EPM_etaDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EPM_etaDoubleSpinBox_1.setSuffix("")
        self.EPM_etaDoubleSpinBox_1.setMinimum(1.01)
        self.EPM_etaDoubleSpinBox_1.setMaximum(10.0)
        self.EPM_etaDoubleSpinBox_1.setSingleStep(0.01)
        self.EPM_etaDoubleSpinBox_1.setObjectName("EPM_etaDoubleSpinBox_1")
        self.horizontalLayout_16.addWidget(self.EPM_etaDoubleSpinBox_1)
        self.EPM_etaDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.EPM_etaGroupBox)
        self.EPM_etaDoubleSpinBox_2.setMinimumSize(QtCore.QSize(0, 25))
        self.EPM_etaDoubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EPM_etaDoubleSpinBox_2.setSuffix("")
        self.EPM_etaDoubleSpinBox_2.setMinimum(1.01)
        self.EPM_etaDoubleSpinBox_2.setMaximum(10.0)
        self.EPM_etaDoubleSpinBox_2.setSingleStep(0.01)
        self.EPM_etaDoubleSpinBox_2.setObjectName("EPM_etaDoubleSpinBox_2")
        self.horizontalLayout_16.addWidget(self.EPM_etaDoubleSpinBox_2)
        self.horizontalLayout_6.addWidget(self.EPM_etaGroupBox)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.EPM_betaCheckBox = QtWidgets.QCheckBox(self.EPM_GroupBox)
        self.EPM_betaCheckBox.setObjectName("EPM_betaCheckBox")
        self.horizontalLayout_7.addWidget(self.EPM_betaCheckBox)
        self.EPM_betaGroupBox = QtWidgets.QGroupBox(self.EPM_GroupBox)
        self.EPM_betaGroupBox.setEnabled(False)
        self.EPM_betaGroupBox.setTitle("")
        self.EPM_betaGroupBox.setObjectName("EPM_betaGroupBox")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.EPM_betaGroupBox)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.EPM_betaDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.EPM_betaGroupBox)
        self.EPM_betaDoubleSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.EPM_betaDoubleSpinBox.setMaximumSize(QtCore.QSize(19999, 19999))
        self.EPM_betaDoubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.EPM_betaDoubleSpinBox.setSuffix("")
        self.EPM_betaDoubleSpinBox.setMinimum(0.01)
        self.EPM_betaDoubleSpinBox.setMaximum(1.0)
        self.EPM_betaDoubleSpinBox.setSingleStep(0.01)
        self.EPM_betaDoubleSpinBox.setObjectName("EPM_betaDoubleSpinBox")
        self.horizontalLayout_17.addWidget(self.EPM_betaDoubleSpinBox)
        self.horizontalLayout_7.addWidget(self.EPM_betaGroupBox)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.EPM_GroupBox, 1, 0, 1, 1)
        self.DM_GroupBox = QtWidgets.QGroupBox(self.tab_4)
        self.DM_GroupBox.setEnabled(False)
        self.DM_GroupBox.setMinimumSize(QtCore.QSize(0, 140))
        self.DM_GroupBox.setMaximumSize(QtCore.QSize(16777215, 10000000))
        self.DM_GroupBox.setTitle("")
        self.DM_GroupBox.setObjectName("DM_GroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.DM_GroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.DM_timeGroupBox = QtWidgets.QGroupBox(self.DM_GroupBox)
        self.DM_timeGroupBox.setEnabled(False)
        self.DM_timeGroupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.DM_timeGroupBox.setTitle("")
        self.DM_timeGroupBox.setObjectName("DM_timeGroupBox")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.DM_timeGroupBox)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.DM_timeLabel = QtWidgets.QLabel(self.DM_timeGroupBox)
        self.DM_timeLabel.setObjectName("DM_timeLabel")
        self.horizontalLayout_22.addWidget(self.DM_timeLabel)
        self.DM_timeDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.DM_timeGroupBox)
        self.DM_timeDoubleSpinBox_1.setMinimumSize(QtCore.QSize(60, 25))
        self.DM_timeDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Kenya))
        self.DM_timeDoubleSpinBox_1.setProperty("showGroupSeparator", False)
        self.DM_timeDoubleSpinBox_1.setSuffix("")
        self.DM_timeDoubleSpinBox_1.setMinimum(0.01)
        self.DM_timeDoubleSpinBox_1.setMaximum(1000000.0)
        self.DM_timeDoubleSpinBox_1.setSingleStep(0.01)
        self.DM_timeDoubleSpinBox_1.setObjectName("DM_timeDoubleSpinBox_1")
        self.horizontalLayout_22.addWidget(self.DM_timeDoubleSpinBox_1)
        self.DM_timeDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.DM_timeGroupBox)
        self.DM_timeDoubleSpinBox_2.setMinimumSize(QtCore.QSize(60, 25))
        self.DM_timeDoubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Kenya))
        self.DM_timeDoubleSpinBox_2.setSuffix("")
        self.DM_timeDoubleSpinBox_2.setMinimum(0.01)
        self.DM_timeDoubleSpinBox_2.setMaximum(1000000.0)
        self.DM_timeDoubleSpinBox_2.setSingleStep(0.01)
        self.DM_timeDoubleSpinBox_2.setObjectName("DM_timeDoubleSpinBox_2")
        self.horizontalLayout_22.addWidget(self.DM_timeDoubleSpinBox_2)
        self.horizontalLayout_9.addWidget(self.DM_timeGroupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.DM_pdGroupBox = QtWidgets.QGroupBox(self.DM_GroupBox)
        self.DM_pdGroupBox.setEnabled(False)
        self.DM_pdGroupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.DM_pdGroupBox.setTitle("")
        self.DM_pdGroupBox.setObjectName("DM_pdGroupBox")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.DM_pdGroupBox)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.DM_pdLabel = QtWidgets.QLabel(self.DM_pdGroupBox)
        self.DM_pdLabel.setObjectName("DM_pdLabel")
        self.horizontalLayout_21.addWidget(self.DM_pdLabel)
        self.DM_pdDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.DM_pdGroupBox)
        self.DM_pdDoubleSpinBox_1.setMinimumSize(QtCore.QSize(0, 25))
        self.DM_pdDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DM_pdDoubleSpinBox_1.setSuffix("")
        self.DM_pdDoubleSpinBox_1.setMinimum(0.01)
        self.DM_pdDoubleSpinBox_1.setMaximum(20.0)
        self.DM_pdDoubleSpinBox_1.setSingleStep(0.01)
        self.DM_pdDoubleSpinBox_1.setObjectName("DM_pdDoubleSpinBox_1")
        self.horizontalLayout_21.addWidget(self.DM_pdDoubleSpinBox_1)
        self.DM_pdDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.DM_pdGroupBox)
        self.DM_pdDoubleSpinBox_2.setMinimumSize(QtCore.QSize(0, 25))
        self.DM_pdDoubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DM_pdDoubleSpinBox_2.setSuffix("")
        self.DM_pdDoubleSpinBox_2.setMinimum(0.01)
        self.DM_pdDoubleSpinBox_2.setMaximum(20.0)
        self.DM_pdDoubleSpinBox_2.setSingleStep(0.01)
        self.DM_pdDoubleSpinBox_2.setObjectName("DM_pdDoubleSpinBox_2")
        self.horizontalLayout_21.addWidget(self.DM_pdDoubleSpinBox_2)
        self.horizontalLayout_8.addWidget(self.DM_pdGroupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.DM_betaCheckBox = QtWidgets.QCheckBox(self.DM_GroupBox)
        self.DM_betaCheckBox.setObjectName("DM_betaCheckBox")
        self.horizontalLayout_10.addWidget(self.DM_betaCheckBox)
        self.DM_betaGroupBox = QtWidgets.QGroupBox(self.DM_GroupBox)
        self.DM_betaGroupBox.setEnabled(False)
        self.DM_betaGroupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.DM_betaGroupBox.setTitle("")
        self.DM_betaGroupBox.setObjectName("DM_betaGroupBox")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.DM_betaGroupBox)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.DM_betaDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.DM_betaGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.DM_betaDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.DM_betaDoubleSpinBox.setSizePolicy(sizePolicy)
        self.DM_betaDoubleSpinBox.setMinimumSize(QtCore.QSize(10, 25))
        self.DM_betaDoubleSpinBox.setMaximumSize(QtCore.QSize(19999, 19999))
        self.DM_betaDoubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DM_betaDoubleSpinBox.setSuffix("")
        self.DM_betaDoubleSpinBox.setMinimum(0.01)
        self.DM_betaDoubleSpinBox.setMaximum(1.0)
        self.DM_betaDoubleSpinBox.setSingleStep(0.01)
        self.DM_betaDoubleSpinBox.setObjectName("DM_betaDoubleSpinBox")
        self.horizontalLayout_20.addWidget(self.DM_betaDoubleSpinBox)
        self.horizontalLayout_10.addWidget(self.DM_betaGroupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.gridLayout_6.addWidget(self.DM_GroupBox, 1, 1, 1, 1)
        self.modelsTabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_25.addWidget(self.modelsTabWidget)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem8)
        self.verticalLayout_5.addWidget(self.modelsFrame)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_51.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.startButton = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(120, 30))
        self.startButton.setMaximumSize(QtCore.QSize(150, 30))
        self.startButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_51.addWidget(self.startButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem9)
        self.calculationsLabel = QtWidgets.QLabel(self.page)
        self.calculationsLabel.setText("")
        self.calculationsLabel.setObjectName("calculationsLabel")
        self.horizontalLayout_51.addWidget(self.calculationsLabel)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_28.addWidget(self.progressBar)
        self.progressBarLabel = QtWidgets.QLabel(self.page)
        self.progressBarLabel.setObjectName("progressBarLabel")
        self.horizontalLayout_28.addWidget(self.progressBarLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setMinimumSize(QtCore.QSize(480, 320))
        self.page_2.setObjectName("page_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ylimDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.ylimDoubleSpinBox_1.setMinimumSize(QtCore.QSize(80, 0))
        self.ylimDoubleSpinBox_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ylimDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ylimDoubleSpinBox_1.setMaximum(3000.99)
        self.ylimDoubleSpinBox_1.setObjectName("ylimDoubleSpinBox_1")
        self.gridLayout_2.addWidget(self.ylimDoubleSpinBox_1, 0, 4, 1, 1)
        self.xlimDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.xlimDoubleSpinBox_1.setMinimumSize(QtCore.QSize(80, 0))
        self.xlimDoubleSpinBox_1.setMaximumSize(QtCore.QSize(80, 40))
        self.xlimDoubleSpinBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.xlimDoubleSpinBox_1.setMaximum(3000.99)
        self.xlimDoubleSpinBox_1.setObjectName("xlimDoubleSpinBox_1")
        self.gridLayout_2.addWidget(self.xlimDoubleSpinBox_1, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 6, 1, 1)
        self.xlimDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.xlimDoubleSpinBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.xlimDoubleSpinBox_2.setMaximumSize(QtCore.QSize(80, 40))
        self.xlimDoubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.xlimDoubleSpinBox_2.setMaximum(3000.99)
        self.xlimDoubleSpinBox_2.setSingleStep(1.0)
        self.xlimDoubleSpinBox_2.setObjectName("xlimDoubleSpinBox_2")
        self.gridLayout_2.addWidget(self.xlimDoubleSpinBox_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.ylimDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.ylimDoubleSpinBox_2.setMinimumSize(QtCore.QSize(80, 0))
        self.ylimDoubleSpinBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ylimDoubleSpinBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ylimDoubleSpinBox_2.setMaximum(3000.99)
        self.ylimDoubleSpinBox_2.setObjectName("ylimDoubleSpinBox_2")
        self.gridLayout_2.addWidget(self.ylimDoubleSpinBox_2, 0, 5, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.goBackButton = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goBackButton.sizePolicy().hasHeightForWidth())
        self.goBackButton.setSizePolicy(sizePolicy)
        self.goBackButton.setMinimumSize(QtCore.QSize(120, 30))
        self.goBackButton.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.goBackButton.setFont(font)
        self.goBackButton.setObjectName("goBackButton")
        self.horizontalLayout_53.addWidget(self.goBackButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem12)
        self.closeButton_2 = QtWidgets.QPushButton(self.page_2)
        self.closeButton_2.setMinimumSize(QtCore.QSize(120, 30))
        self.closeButton_2.setMaximumSize(QtCore.QSize(150, 50))
        self.closeButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.closeButton_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.closeButton_2.setObjectName("closeButton_2")
        self.horizontalLayout_53.addWidget(self.closeButton_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_53, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkButton = QtWidgets.QPushButton(self.page_2)
        self.checkButton.setEnabled(False)
        self.checkButton.setMinimumSize(QtCore.QSize(200, 30))
        self.checkButton.setMaximumSize(QtCore.QSize(200, 50))
        self.checkButton.setObjectName("checkButton")
        self.gridLayout_4.addWidget(self.checkButton, 1, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 3, 1, 1, 1)
        self.savePushButton = QtWidgets.QPushButton(self.page_2)
        self.savePushButton.setEnabled(False)
        self.savePushButton.setMinimumSize(QtCore.QSize(200, 30))
        self.savePushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.savePushButton.setObjectName("savePushButton")
        self.gridLayout_4.addWidget(self.savePushButton, 3, 3, 1, 1)
        self.ModelsPushButton = QtWidgets.QPushButton(self.page_2)
        self.ModelsPushButton.setEnabled(False)
        self.ModelsPushButton.setMinimumSize(QtCore.QSize(200, 30))
        self.ModelsPushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.ModelsPushButton.setObjectName("ModelsPushButton")
        self.gridLayout_4.addWidget(self.ModelsPushButton, 3, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.page_2)
        self.deleteButton.setEnabled(False)
        self.deleteButton.setMinimumSize(QtCore.QSize(200, 30))
        self.deleteButton.setMaximumSize(QtCore.QSize(200, 50))
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_4.addWidget(self.deleteButton, 3, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 4, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setObjectName("gridLayout")
        self.plotWidget = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.plotWidget.setMaximumSize(QtCore.QSize(100000, 100000))
        self.plotWidget.setObjectName("plotWidget")
        self.plotWidgetLayout = QtWidgets.QVBoxLayout(self.plotWidget)
        self.plotWidgetLayout.setObjectName("plotWidgetLayout")
        self.gridLayout.addWidget(self.plotWidget, 0, 0, 1, 1)
        self.plotListWidget = QtWidgets.QListWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotListWidget.sizePolicy().hasHeightForWidth())
        self.plotListWidget.setSizePolicy(sizePolicy)
        self.plotListWidget.setMinimumSize(QtCore.QSize(100, 230))
        self.plotListWidget.setMaximumSize(QtCore.QSize(250, 10000000))
        self.plotListWidget.setSizeIncrement(QtCore.QSize(100, 100))
        self.plotListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plotListWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.plotListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.plotListWidget.setObjectName("plotListWidget")
        self.gridLayout.addWidget(self.plotListWidget, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.widget1, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setMaximumSize(QtCore.QSize(10000000, 85))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.paramsTextBrowser = QtWidgets.QTextBrowser(self.frame)
        self.paramsTextBrowser.setMinimumSize(QtCore.QSize(0, 25))
        self.paramsTextBrowser.setMaximumSize(QtCore.QSize(420, 30))
        self.paramsTextBrowser.setObjectName("paramsTextBrowser")
        self.gridLayout_9.addWidget(self.paramsTextBrowser, 0, 5, 1, 1)
        self.paramsLabel = QtWidgets.QLabel(self.frame)
        self.paramsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.paramsLabel.setObjectName("paramsLabel")
        self.gridLayout_9.addWidget(self.paramsLabel, 0, 4, 1, 1)
        self.mseLabel = QtWidgets.QLabel(self.frame)
        self.mseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mseLabel.setObjectName("mseLabel")
        self.gridLayout_9.addWidget(self.mseLabel, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 0, 8, 1, 1)
        self.mseTextBrowser = QtWidgets.QTextBrowser(self.frame)
        self.mseTextBrowser.setMinimumSize(QtCore.QSize(50, 25))
        self.mseTextBrowser.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mseTextBrowser.setSizeIncrement(QtCore.QSize(50, 0))
        self.mseTextBrowser.setObjectName("mseTextBrowser")
        self.gridLayout_9.addWidget(self.mseTextBrowser, 1, 1, 1, 1)
        self.betaTextBrowser = QtWidgets.QTextBrowser(self.frame)
        self.betaTextBrowser.setMinimumSize(QtCore.QSize(0, 25))
        self.betaTextBrowser.setMaximumSize(QtCore.QSize(100, 30))
        self.betaTextBrowser.setObjectName("betaTextBrowser")
        self.gridLayout_9.addWidget(self.betaTextBrowser, 0, 10, 1, 1)
        self.betaLabel = QtWidgets.QLabel(self.frame)
        self.betaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.betaLabel.setObjectName("betaLabel")
        self.gridLayout_9.addWidget(self.betaLabel, 0, 9, 1, 1)
        self.modelLabel = QtWidgets.QLabel(self.frame)
        self.modelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modelLabel.setObjectName("modelLabel")
        self.gridLayout_9.addWidget(self.modelLabel, 0, 0, 1, 1)
        self.modelTextBrowser = QtWidgets.QTextBrowser(self.frame)
        self.modelTextBrowser.setMinimumSize(QtCore.QSize(0, 25))
        self.modelTextBrowser.setMaximumSize(QtCore.QSize(100, 30))
        self.modelTextBrowser.setObjectName("modelTextBrowser")
        self.gridLayout_9.addWidget(self.modelTextBrowser, 0, 1, 1, 1)
        self.meLabel = QtWidgets.QLabel(self.frame)
        self.meLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.meLabel.setObjectName("meLabel")
        self.gridLayout_9.addWidget(self.meLabel, 1, 4, 1, 1)
        self.meTextBrowser = QtWidgets.QTextBrowser(self.frame)
        self.meTextBrowser.setMinimumSize(QtCore.QSize(80, 25))
        self.meTextBrowser.setMaximumSize(QtCore.QSize(80, 25))
        self.meTextBrowser.setObjectName("meTextBrowser")
        self.gridLayout_9.addWidget(self.meTextBrowser, 1, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem14, 0, 7, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 0, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem16, 1, 3, 1, 1)
        self.gridLayout_8.addWidget(self.frame, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)

        self.retranslateUi(Gui)
        self.stackedWidget.setCurrentIndex(0)
        self.modelsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Gui)

    def retranslateUi(self, Gui):
        _translate = QtCore.QCoreApplication.translate
        Gui.setWindowTitle(_translate("Gui", "Gui"))
        self.plotsButton.setText(_translate("Gui", "Plots"))
        self.closeButton.setText(_translate("Gui", "Close"))
        self.inputFileText.setText(_translate("Gui", "Select input file"))
        self.showInputDataButton.setText(_translate("Gui", "Show Data"))
        self.outputFileText.setText(_translate("Gui", "Select observations file"))
        self.showObservationsDataButton.setText(_translate("Gui", "Show Data"))
        self.inputFileButton.setText(_translate("Gui", "Browse"))
        self.outputFileButton.setText(_translate("Gui", "Browse"))
        self.aphaInputFileText.setText(_translate("Gui", "Infiltration coefficient α "))
        self.uncertaintyCheckBox.setText(_translate("Gui", "Calculate params uncertainty"))
        self.PFMcheckBox.setText(_translate("Gui", "Piston Flow Model"))
        self.EMcheckBox.setText(_translate("Gui", "Exponential Model"))
        self.EMwrnLabel.setWhatsThis(_translate("Gui", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.PFM_timeLabel.setText(_translate("Gui", "Transit time range"))
        self.PFM_betaCheckBox.setText(_translate("Gui", "β parameter"))
        self.EM_timeLabel.setText(_translate("Gui", "Transit time range"))
        self.EM_betaCheckBox.setText(_translate("Gui", "β parameter"))
        self.modelsTabWidget.setTabText(self.modelsTabWidget.indexOf(self.widget), _translate("Gui", "1 parameter"))
        self.EPMcheckBox.setText(_translate("Gui", "Exponential Piston Flow Model"))
        self.DMcheckBox.setText(_translate("Gui", "Dispersion Model"))
        self.EPM_timeLabel.setText(_translate("Gui", "Transit time range"))
        self.EPM_etaLabel.setText(_translate("Gui", "η range"))
        self.EPM_betaCheckBox.setText(_translate("Gui", "β parameter"))
        self.DM_timeLabel.setText(_translate("Gui", "Transit time range"))
        self.DM_pdLabel.setText(_translate("Gui", "PD range"))
        self.DM_betaCheckBox.setText(_translate("Gui", "β parameter"))
        self.modelsTabWidget.setTabText(self.modelsTabWidget.indexOf(self.tab_4), _translate("Gui", "2 parameters"))
        self.startButton.setText(_translate("Gui", "Run"))
        self.progressBarLabel.setText(_translate("Gui", "0 %"))
        self.label.setText(_translate("Gui", "X-Axis"))
        self.label_2.setText(_translate("Gui", "Y-Axis"))
        self.goBackButton.setText(_translate("Gui", "Configuration"))
        self.closeButton_2.setToolTip(_translate("Gui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.closeButton_2.setText(_translate("Gui", "Close"))
        self.checkButton.setText(_translate("Gui", "Check all"))
        self.savePushButton.setText(_translate("Gui", "Save to csv"))
        self.ModelsPushButton.setText(_translate("Gui", "Data table"))
        self.deleteButton.setText(_translate("Gui", "Remove selected"))
        self.paramsTextBrowser.setHtml(_translate("Gui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.paramsLabel.setText(_translate("Gui", "Parameters"))
        self.mseLabel.setText(_translate("Gui", "MSE"))
        self.betaTextBrowser.setHtml(_translate("Gui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.betaLabel.setText(_translate("Gui", "β parameter"))
        self.modelLabel.setText(_translate("Gui", "Model Type"))
        self.modelTextBrowser.setHtml(_translate("Gui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.meLabel.setText(_translate("Gui", "Model Efficiency"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gui = QtWidgets.QWidget()
    ui = Ui_Gui()
    ui.setupUi(Gui)
    Gui.show()
    sys.exit(app.exec_())

